# Generated by Django 5.1 on 2024-09-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesData',
            fields=[
                ('country', models.TextField(db_column='CountryName')),
                ('year', models.TextField(db_column='Year')),
                ('life_expectancy', models.TextField(blank=True, db_column='LifeEx')),
                ('population', models.TextField(blank=True, db_column='Population')),
                ('dummy_id', models.IntegerField(db_column='dummyID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Countries',
                'managed': False,
            },
        ),
    ]
